### ISSUE TITLE
 Empty reply from server

### ISSUE THREAD

**Issue by towerbit** [andresribeiro/nsfwjs-docker#4]
After I posted a jpg file by curl like this,
`curl -F "content=@img1.jpg" "http://localhost:3333/single/multipart-form"`
I got the replay 
`curl: (52) Empty reply from server`
And then the server app has been terminated.

**Comment by andresribeiro** [comment]
Hey @towerbit! We migrated from Express to Fastify 🚀. Could you download the latest version and check if the error is still occurring?

**Comment by andresribeiro** [comment]
Closed as stale. Feel free to open a new issue if this problem persist on latest version
